### ISSUE TITLE
Separate configuration items from xsnip.c

### ISSUE THREAD

**Issue by nathanzachary** [ws-kj/xsnip#3]
Hello,

I'm working on packaging xsnip within Gentoo Linux, and have a couple recommendations that may make it more portable/manageable for distribution maintainers.

Firstly, I think it would be helpful to separate the configuration directives from xsnip.c into a separate file (e.g. xsnip_config.h) so that end-users can have a saved configuration that can be patched in when compiling.

Secondly, it would be good to have an "official" release so that the package can be downloaded as a tar.gz for unpacking.

Thank you for your work!

Cheers,
Nathan Zachary

**Comment by ws-kj** [comment]
Thanks for your interest in the project! The single file config is definitely not an ideal solution, and I'm planning on changing that. Currently I'm torn between implementing a solution as you describe it, or creating a dedicated config file so that the program won't have to be recompiled (in a default of /etc or something). There is more interest in the project than I initially thought there would be, so once I patch a few things I'll create a release.

**Comment by nathanzachary** [comment]
Wonderful news!  The dedicated configuration file would ultimately be a better solution, and I would personally recommend having it on a per-user basis under /home/$USER/.config/xsnip/, but that choice is yours.  I will hold off on the Gentoo ebuild until you have an "official" release that incorporates these changes.

This is a cool project, and I'm excited to see how it develops and progresses!

Cheers,
Nathan Zachary

**Comment by ws-kj** [comment]
I've published a release with a separate config header and all of the features I plan to add for the time being.
