### ISSUE TITLE
Incompatible with OpenBSD

### ISSUE THREAD

**Issue by jtbx** [ws-kj/xsnip#6]
The Makefile is not compatible with OpenBSD.
After I set ${CC} to `cc` in the Makefile, `gmake` (GNU make) gives the following error:

```
cc -o xsnip xsnip.c -g -I. -lX11 -lpng
xsnip.c:26:10: fatal error: 'png.h' file not found
#include <png.h>
         ^~~~~~~
1 error generated.
gmake: *** [Makefile:14: xsnip] Error 1
```

png.h on OpenBSD is located at /usr/local/include/png.h.
Projects like dwm achieve cross-platform compatibility by including a few commented out lines that once uncommented, will make make (or cc) known to the real location of the libraries.

I might try to fix this issue myself and submit a PR.

**Comment by semarie** [comment]
On OpenBSD, `cc` doesn't search by default under `/usr/local` for include files or libraries (see [clang-local(1) man page](https://man.openbsd.org/clang-local.1)).

if you want to use `png` library without hardcoding paths, it is preferable to use [`pkg-config`](https://man.openbsd.org/pkg-config.1) to know the arguments to use:

```
$ pkg-config --cflags libpng
-I/usr/local/include/libpng16
$ pkg-config --libs libpng         
-L/usr/local/lib -lpng -lz
```

**Comment by jtbx** [comment]
Oh wow, thanks!
I modified the Makefile a little bit and it ended up like [this](https://paste.rs/iW7). After running gmake, I got no errors but the resulting executable just outputs
`Authorization required, but no authorization protocol specified`
`zsh: segmentation fault (core dumped)  xsnip`

I'm a bit confused by this.

**Comment by ws-kj** [comment]
If I had to guess, you're probably getting `Authorization required, but no authorization protocol specified` because you either installed the program as root or are running it as root, while your X server is running under your user. I'm pretty sure that the usual fix for this is to do something with `xhost`, but I'm not really sure.
I'm sorry that xsnip is causing all these issues on BSD. If you can get the Makefile working for you, I'd be happy to merge it. If I had known what I was doing when I wrote this, I probably would've just used CMake and saved some hassle.

**Comment by jtbx** [comment]
I re-cloned the repository and rebuilt it again, and still no luck. I disabled my login manager, and now xsnip's working. Thanks!
